name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Package
      run: |
        mkdir -p package/cloudinitwin
        cp target/release/cloudinitwin.exe package/cloudinitwin/CloudInitWin.exe
        cp scripts/* package/cloudinitwin
    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: CloudInitWin
        path: package/cloudinitwin/
