name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:

  default_job:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Test
      run: cargo test --verbose
    - name: Package
      shell: pwsh
      run: |
        cargo build --release --verbose
        ./package.ps1
    - name: Release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      with:
        files: cloudinitwin.zip
